apiVersion: v1
items:
- apiVersion: kind.x-k8s.io/v1alpha4
  kind: Machine
  metadata:
    labels:
      set: master
    name: master-0
    namespace: weavek8sops
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
          address: 10.61.0.22
          port: 22
        public:
          address: 127.0.0.1
          port: 2222
- apiVersion: kind.x-k8s.io/v1alpha4
  kind: Machine
  metadata:
    labels:
      set: worker
    name: worker-0
    namespace: weavek8sops
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
          address: 10.61.0.23
          port: 22
        public:
          address: 127.0.0.1
          port: 2223
kind: List
